=== Aniketchaurasia97/iwt/week4/schemastructure.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="mentors">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="mentor" maxOccurs="6" minOccurs="1" >
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="name" type="xsd:string" minOccurs="1"/>
                            <xsd:element name="designation">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:maxLength value="50"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="subjects" type="xsd:string" minOccurs="1"/>
                            <xsd:element name="yearsOfExp" type="xsd:integer"/>

                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:integer" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Aniketchaurasia97/iwt/week4/data.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<mentors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schemastructure.xsd">

    <mentor id="1">
        <name>Dr. Sundeep Sood</name>
        <designation>Head of Dept.</designation>
        <subjects>C, Ds, Cloud</subjects>
        <yearsOfExp>10</yearsOfExp>
    </mentor>
    <mentor id="2">
        <name>Dr. Munish Bhatia</name>
        <designation>Assistant Professor</designation>
        <subjects>Cn, Iwt, OS</subjects>
        <yearsOfExp>8</yearsOfExp>
    </mentor>
    <mentor id="3">
        <name>Prof. Anhsu Parashar</name>
        <designation>Assistant Proffessor</designation>
        <subjects>DBMS, AI, DAA</subjects>
        <yearsOfExp>9</yearsOfExp>
    </mentor>
    <mentor id="4">
        <name>Dr. Sarika jain</name>
        <designation>Professor</designation>
        <subjects>DM, COA, SE</subjects>
        <yearsOfExp>12</yearsOfExp>
    </mentor>
    <mentor id="5">
        <name>Dr. Kapil Gupta</name>
        <designation>Assistant proffessor</designation>
        <subjects>Python,DA,Java</subjects>
        <yearsOfExp>1</yearsOfExp>
    </mentor>
</mentors>
